### ISSUE TITLE
Text wrapped in a b or span is not clickable

### ISSUE THREAD

**Issue by rippo** [kanine/autocompleteBS#7]
If the dropdown contains HTML tags such as a `B` tag or `SPAN` tag etc then it is impossible to click on the `B` tag to get the list to fire the callback.

https://github.com/kanine/autocompleteBS/blob/6d09c786689684c3f121f2f691f1d5c00bd931ae/js/autocompleteBS.js#L80-L82

A quick fix to this would be to check that if the `e.target` is not a `div` then get thr parent. e.g.

```js
let selectedElement = e.target;
//Fix if user clicks the `b` tag etc
//console.log(e.target.localName);
if (e.target.localName !== "div")
    selectedElement = e.target.parentElement;
```

![2022-04-21_10-17-37](https://user-images.githubusercontent.com/772549/164423986-f512075a-b7fc-492a-a533-9e8b8df92bdd.png)

**Comment by kanine** [comment]
That looks like a pretty simple change thanks, I'll try and push something later today. It's a bit of a struggle for time at the moment with so many projects on the go.

**Comment by kanine** [comment]
Change applied in https://github.com/kanine/autocompleteBS/commit/53ecc074a7cae3dd9326e1a3e11539b9d11d53e4
