### ISSUE TITLE
Demos are not working

### ISSUE THREAD

**Issue by DerekWSmith** [kanine/autocompleteBS#8]
Just thought you'd like to know.
It's a good-looking project, I'd be keen to use!

**Comment by kanine** [comment]
Thanks, I'll have to take a look at the demos maybe the service behind it got discontinued.

**Comment by kanine** [comment]
Should be sorted now with [#275eec8](https://github.com/kanine/autocompleteBS/commit/275eec8662f288bdaf7e35a74afe0e954b012155)
